@startuml
set separator none
title System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

Person(Dealer, "Dealer", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
Person(WorkshopStaff, "Workshop Staff", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
Person(Administrator, "Administrator", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
System(ReferentialSystem, "Referential System", $descr="Wecare-like referential provider", $tags="", $link="")
System(LoyaltyPrograms, "Loyalty Programs", $descr="Loyalty program adapter", $tags="", $link="")
System(EOrdering, "E-Ordering", $descr="E-ordering adapter", $tags="", $link="")
System(ETax, "E-Tax", $descr="E-tax adapter", $tags="", $link="")
System(TEDSCoreSystem, "TEDS Core System", $descr="DOS platform including microservices and core business logic", $tags="", $link="")
System(DCPMobileApplication, "DCP Mobile Application", $descr="Mobile login application", $tags="", $link="")
System(CRMandBISystem, "CRM and BI System", $descr="CRM and Business Intelligence platform", $tags="", $link="")

Rel(ReferentialSystem, TEDSCoreSystem, "Stores referential", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, LoyaltyPrograms, "Requests available coupons", $techn="kafka", $tags="", $link="")
Rel(LoyaltyPrograms, TEDSCoreSystem, "Stores loyalty data", $techn="", $tags="", $link="")
Rel(EOrdering, TEDSCoreSystem, "Stores eOrdering data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, ETax, "Sends tax data", $techn="kafka", $tags="", $link="")
Rel(ETax, TEDSCoreSystem, "Stores taxation data", $techn="", $tags="", $link="")
Rel(DCPMobileApplication, TEDSCoreSystem, "Exchanges data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, DCPMobileApplication, "Exchanges data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, CRMandBISystem, "Stores reporting data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, Dealer, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, WorkshopStaff, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, Administrator, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(Dealer, DCPMobileApplication, "Manages stores, creates quotations", $techn="", $tags="", $link="")
Rel(Administrator, DCPMobileApplication, "Manages system configuration, create staff users", $techn="", $tags="", $link="")
Rel(WorkshopStaff, DCPMobileApplication, "Performs data entry, performs services, creates quotations", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml