@startuml
set separator none
title HubSpot CRM – Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System(TDataPlatform, "T+ Data Platform", $descr="Reporting data platform & CRM programs", $tags="", $link="")
System(Infobip, "Infobip", $descr="Enabler for messaging platforms", $tags="", $link="")

Container_Boundary("HubSpot.Hubspotcrm_boundary", "Hubspot-crm", $tags="") {
  Component(HubSpot.Hubspotcrm.ReadsTDPtoapplymarketingrules, "Reads TDP to apply marketing rules", $techn="", $descr="", $tags="", $link="")
  Component(HubSpot.Hubspotcrm.ConnectstoInfobipformessaging, "Connects to Infobip for messaging", $techn="", $descr="", $tags="", $link="")
}

Rel(TDataPlatform, HubSpot.Hubspotcrm.ReadsTDPtoapplymarketingrules, "Provides CRM data", $techn="", $tags="", $link="")
Rel(HubSpot.Hubspotcrm.ConnectstoInfobipformessaging, Infobip, "Sends/receives customer messages", $techn="", $tags="", $link="")
Rel(Infobip, HubSpot.Hubspotcrm.ConnectstoInfobipformessaging, "SSends customer replies back to Hubspot", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml