@startuml
set separator none
title Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(TEDSCoreSystem, "TEDS Core System", $descr="DOS platform including microservices and core business logic", $tags="", $link="")
System(ThailandiCare, "Thailand iCare", $descr="Thailand iCare loyalty program", $tags="", $link="")
System(KoreaLoyalty, "Korea Loyalty", $descr="Korea loyalty program", $tags="", $link="")
System(OtherLoyalty, "Other Loyalty", $descr="Other loyalty program", $tags="", $link="")

System_Boundary("LoyaltyPrograms_boundary", "Loyalty Programs", $tags="") {
  Container(LoyaltyPrograms.TEDSLoyalty, "TEDS Loyalty", $techn="", $descr="TEDS loyalty program", $tags="", $link="")
}

Rel(ThailandiCare, LoyaltyPrograms.TEDSLoyalty, "Gets available coupons", $techn="API", $tags="", $link="")
Rel(KoreaLoyalty, LoyaltyPrograms.TEDSLoyalty, "Gets available coupons", $techn="API", $tags="", $link="")
Rel(OtherLoyalty, LoyaltyPrograms.TEDSLoyalty, "Gets available coupons", $techn="API", $tags="", $link="")
Rel(LoyaltyPrograms.TEDSLoyalty, TEDSCoreSystem, "Provides available coupons", $techn="kafka", $tags="", $link="")

SHOW_LEGEND(true)
@enduml