@startuml
set separator none
title Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(HubSpot, "HubSpot", $descr="CRM & marketing automation", $tags="", $link="")
System(MessagingPlatforms, "Messaging Platforms", $descr="Line, WhatsApp, etc.", $tags="", $link="")

System_Boundary("Infobip_boundary", "Infobip", $tags="") {
  Container(Infobip.Infobipcrm, "Infobip-crm", $techn="", $descr="infobip enabler", $tags="", $link="")
}

Rel(HubSpot, Infobip.Infobipcrm, "Sends/receives customer messages", $techn="", $tags="", $link="")
Rel(Infobip.Infobipcrm, MessagingPlatforms, "Sends messages to customers", $techn="", $tags="", $link="")
Rel(MessagingPlatforms, Infobip.Infobipcrm, "Sends customer replies back to Infobip", $techn="", $tags="", $link="")
Rel(Infobip.Infobipcrm, HubSpot, "SSends customer replies back to Hubspot", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml