@startuml
set separator none
title API Application – Components

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container(TEDSCoreSystem.SinglePageApplication, "Single-Page Application", $techn="React + TypeScript", $descr="Internet banking UI in the browser", $tags="", $link="")
Container(TEDSCoreSystem.MobileApp, "Mobile App", $techn="Flutter", $descr="Limited functionality on mobile devices", $tags="", $link="")

Container_Boundary("TEDSCoreSystem.APIApplication_boundary", "API Application", $tags="") {
  Component(TEDSCoreSystem.APIApplication.SignInController, "Sign In Controller", $techn="Spring MVC RestController", $descr="Allows users to sign in", $tags="", $link="")
  Component(TEDSCoreSystem.APIApplication.AccountsController, "Accounts Controller", $techn="Spring MVC RestController", $descr="Account summary & history", $tags="", $link="")
  Component(TEDSCoreSystem.APIApplication.TransferController, "Transfer Controller", $techn="Spring MVC RestController", $descr="Handles payments/transfers", $tags="", $link="")
  Component(TEDSCoreSystem.APIApplication.SecurityComponent, "Security Component", $techn="Spring Security", $descr="Authentication & authorization", $tags="", $link="")
  Component(TEDSCoreSystem.APIApplication.MainframeFacade, "Mainframe Facade", $techn="Java", $descr="Adapter to legacy mainframe", $tags="", $link="")
}

Rel(TEDSCoreSystem.SinglePageApplication, TEDSCoreSystem.APIApplication.SignInController, "POST /signin", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem.SinglePageApplication, TEDSCoreSystem.APIApplication.AccountsController, "GET /accounts", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem.SinglePageApplication, TEDSCoreSystem.APIApplication.TransferController, "POST /transfer", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem.MobileApp, TEDSCoreSystem.APIApplication.SignInController, "POST /signin", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem.MobileApp, TEDSCoreSystem.APIApplication.AccountsController, "GET /accounts", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem.MobileApp, TEDSCoreSystem.APIApplication.TransferController, "POST /transfer", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem.APIApplication.SignInController, TEDSCoreSystem.APIApplication.SecurityComponent, "Uses", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.APIApplication.AccountsController, TEDSCoreSystem.APIApplication.MainframeFacade, "Uses", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.APIApplication.TransferController, TEDSCoreSystem.APIApplication.MainframeFacade, "Uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml