@startuml
set separator none
title Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(TEDSCoreSystem, "TEDS Core System", $descr="DOS platform including microservices and core business logic", $tags="", $link="")
System(ThailandMDO, "Thailand MDO", $descr="Thailand MDO e-ordering program", $tags="", $link="")
System(KoreaSANA, "Korea SANA", $descr="Korea SANA e-ordering program", $tags="", $link="")
System(OtherEOrdering, "Other E-Ordering", $descr="Other e-ordering program", $tags="", $link="")

System_Boundary("EOrdering_boundary", "E-Ordering", $tags="") {
  Container(EOrdering.TEDSEOrdering, "TEDS E-Ordering", $techn="", $descr="TEDS e-ordering program", $tags="", $link="")
}

Rel(ThailandMDO, EOrdering.TEDSEOrdering, "Gets available E-orders", $techn="API", $tags="", $link="")
Rel(KoreaSANA, EOrdering.TEDSEOrdering, "Gets available E-orders", $techn="API", $tags="", $link="")
Rel(OtherEOrdering, EOrdering.TEDSEOrdering, "Gets available E-orders", $techn="API", $tags="", $link="")
Rel(EOrdering.TEDSEOrdering, TEDSCoreSystem, "Provides available E-orders", $techn="kafka", $tags="", $link="")

SHOW_LEGEND(true)
@enduml