@startuml
set separator none
title System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

Person(Dealer, "Dealer", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
Person(Administrator, "Administrator", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
System(ReferentialSystem, "Referential System", $descr="Wecare-like referential provider", $tags="", $link="")
Person(Customer, "Customer", $descr="Receives NPS surveys, messages, quotations", $tags="", $link="")
System(LoyaltyPrograms, "Loyalty Programs", $descr="Loyalty program adapter", $tags="", $link="")
System(DCPMobileApplication, "DCP Mobile Application", $descr="Mobile login application", $tags="", $link="")
System(EOrdering, "E-Ordering", $descr="E-ordering adapter", $tags="", $link="")
System(TaxationAdapter, "Taxation Adapter", $descr="Downstream tax processing & government linking", $tags="", $link="")
System(TDataPlatform, "T+ Data Platform", $descr="Reporting data platform & CRM programs", $tags="", $link="")
System(TEDSCoreSystem, "TEDS Core System", $descr="DOS platform including microservices and core business logic", $tags="", $link="")

Rel(ReferentialSystem, TEDSCoreSystem, "Provides referential data", $techn="kafka", $tags="", $link="")
Rel(LoyaltyPrograms, TEDSCoreSystem, "Provides available coupons", $techn="kafka", $tags="", $link="")
Rel(EOrdering, TEDSCoreSystem, "Sends purchase orders", $techn="kafka", $tags="", $link="")
Rel(TEDSCoreSystem, TaxationAdapter, "Sends tax data", $techn="kafka", $tags="", $link="")
Rel(TaxationAdapter, TEDSCoreSystem, "Provides government reference ID", $techn="kafka", $tags="", $link="")
Rel(TEDSCoreSystem, TDataPlatform, "Sends reporting data", $techn="kafka", $tags="", $link="")
Rel(TEDSCoreSystem, Dealer, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, Administrator, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(Customer, TEDSCoreSystem, "Uses", $techn="HTTPS", $tags="", $link="")
Rel(Dealer, DCPMobileApplication, "Uses", $techn="", $tags="", $link="")
Rel(DCPMobileApplication, TEDSCoreSystem, "Authenticates & exchanges data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem, DCPMobileApplication, "Authenticates & exchanges data", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml