@startuml
set separator none
title Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(Dealer, "Dealer", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
Person(WorkshopStaff, "Workshop Staff", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
Person(Administrator, "Administrator", $descr="Performs manual data entry, manages tires & services, creates quotations", $tags="", $link="")
System(ReferentialSystem, "Referential System", $descr="Wecare-like referential provider", $tags="", $link="")
System(LoyaltyPrograms, "Loyalty Programs", $descr="Loyalty program adapter", $tags="", $link="")
System(EOrdering, "E-Ordering", $descr="E-ordering adapter", $tags="", $link="")
System(ETax, "E-Tax", $descr="E-tax adapter", $tags="", $link="")
System(DCPMobileApplication, "DCP Mobile Application", $descr="Mobile login application", $tags="", $link="")
System(TDataPlatform, "T+ Data Platform", $descr="Reporting data platform & CRM programs", $tags="", $link="")

System_Boundary("TEDSCoreSystem_boundary", "TEDS Core System", $tags="") {
  AddBoundaryTag("Backend", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_1, "Backend", $tags="Backend") {
      AddBoundaryTag("Backend/Core-Services", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
      Boundary(group_2, "Core-Services", $tags="Backend/Core-Services") {
        Container(TEDSCoreSystem.tedsserviceaftersales, "teds-service-aftersales", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
        Container(TEDSCoreSystem.tedsservicecustomer, "teds-service-customer", $techn="React + TypeScript", $descr="Provides all banking functionality in the browser", $tags="", $link="")
        Container(TEDSCoreSystem.tedsservicefinance, "teds-service-finance", $techn="React + TypeScript", $descr="Provides all banking functionality in the browser", $tags="", $link="")
        Container(TEDSCoreSystem.tedsservicesupplychain, "teds-service-supplychain", $techn="React + TypeScript", $descr="Provides all banking functionality in the browser", $tags="", $link="")
        Container(TEDSCoreSystem.tedsservicesku, "teds-service-sku", $techn="React + TypeScript", $descr="Provides all banking functionality in the browser", $tags="", $link="")
      }

      AddBoundaryTag("Backend/Gateway", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
      Boundary(group_3, "Gateway", $tags="Backend/Gateway") {
        Container(TEDSCoreSystem.systemfoundation, "systemfoundation", $techn="React + TypeScript", $descr="Provides all banking functionality in the browser", $tags="", $link="")
        Container(TEDSCoreSystem.openapi, "openapi", $techn="React + TypeScript", $descr="Provides all banking functionality in the browser", $tags="", $link="")
        Container(TEDSCoreSystem.tedsserviceweb, "teds-service-web", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
      }

      AddBoundaryTag("Backend/non-core-services", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
      Boundary(group_4, "non-core-services", $tags="Backend/non-core-services") {
        Container(TEDSCoreSystem.tedsservicereport, "teds-service-report", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
        Container(TEDSCoreSystem.tedsservicescheduler, "teds-service-scheduler", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
      }

      AddBoundaryTag("Backend/search-acceleration", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
      Boundary(group_5, "search-acceleration", $tags="Backend/search-acceleration") {
        Container(TEDSCoreSystem.tedsservicesearch, "teds-service-search", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
      }

  }

  AddBoundaryTag("Frontend", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_6, "Frontend", $tags="Frontend") {
    Container(TEDSCoreSystem.tedsservicepc, "teds-service-pc", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
    Container(TEDSCoreSystem.tedsservicemobile, "teds-service-mobile", $techn="React + TypeScript", $descr="Provides all banking functionality in the browser", $tags="", $link="")
  }

  AddBoundaryTag("external-communication", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_7, "external-communication", $tags="external-communication") {
    Container(TEDSCoreSystem.kafka, "kafka", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
    Container(TEDSCoreSystem.APIM, "APIM", $techn="Java + Spring Boot", $descr="Serves static content and the SPA", $tags="", $link="")
  }

  Container(TEDSCoreSystem.CDN, "CDN", $techn="", $descr="Serves static content and the SPA", $tags="", $link="")
  ContainerDb(TEDSCoreSystem.sqlproxy, "sqlproxy", $techn="", $descr="medium performance database", $tags="", $link="")
  ContainerDb(TEDSCoreSystem.reportingdatabase, "reporting-database", $techn="", $descr="medium performance database", $tags="", $link="")
  ContainerDb(TEDSCoreSystem.coredatabase, "core-database", $techn="", $descr="high performance database", $tags="", $link="")
}

Rel(TEDSCoreSystem.tedsservicepc, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicemobile, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsserviceweb, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.systemfoundation, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsserviceaftersales, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicecustomer, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicefinance, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicesupplychain, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicesku, TEDSCoreSystem.sqlproxy, "stores transaction data to core database", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.sqlproxy, TEDSCoreSystem.tedsservicesearch, "Enables searching transaction data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.sqlproxy, TEDSCoreSystem.coredatabase, "Stores transactional data", $techn="", $tags="", $link="")
Rel(ReferentialSystem, TEDSCoreSystem.coredatabase, "Stores referential", $techn="", $tags="", $link="")
Rel(ReferentialSystem, TEDSCoreSystem.tedsservicesku, "Provides referential data", $techn="kafka", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicecustomer, LoyaltyPrograms, "Requests available coupons", $techn="kafka", $tags="", $link="")
Rel(LoyaltyPrograms, TEDSCoreSystem.coredatabase, "Stores loyalty data", $techn="", $tags="", $link="")
Rel(LoyaltyPrograms, TEDSCoreSystem.tedsservicecustomer, "Provides available coupons", $techn="kafka", $tags="", $link="")
Rel(EOrdering, TEDSCoreSystem.coredatabase, "Stores eOrdering data", $techn="", $tags="", $link="")
Rel(EOrdering, TEDSCoreSystem.tedsservicesupplychain, "Provides available E-orders", $techn="kafka", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicefinance, ETax, "Sends tax data", $techn="kafka", $tags="", $link="")
Rel(ETax, TEDSCoreSystem.coredatabase, "Stores taxation data", $techn="", $tags="", $link="")
Rel(ETax, TEDSCoreSystem.tedsservicefinance, "Provides government reference ID", $techn="kafka", $tags="", $link="")
Rel(DCPMobileApplication, TEDSCoreSystem.tedsservicemobile, "Exchanges data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicemobile, DCPMobileApplication, "Exchanges data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicepc, TEDSCoreSystem.coredatabase, "Stores credentials", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.coredatabase, DCPMobileApplication, "Authenticates users", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.coredatabase, TEDSCoreSystem.tedsservicescheduler, "Schedules copy of transaction data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicescheduler, TDataPlatform, "Stores reporting data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.CDN, Dealer, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.CDN, WorkshopStaff, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.CDN, Administrator, "Gets frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.CDN, TEDSCoreSystem.tedsservicepc, "Gives frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.CDN, TEDSCoreSystem.tedsservicemobile, "Gives frontend assets", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicepc, TEDSCoreSystem.tedsserviceweb, "Exchanges data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.tedsservicemobile, TEDSCoreSystem.tedsserviceweb, "Exchanges data", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.kafka, TEDSCoreSystem.openapi, "Uses", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.APIM, TEDSCoreSystem.openapi, "Uses", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsserviceaftersales, "Connects microservices", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsservicecustomer, "Connects microservices", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsservicefinance, "Connects microservices", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsservicesupplychain, "Connects microservices", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsservicesku, "Connects microservices", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsservicesearch, "Connects microservices", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsservicereport, "Connects microservices", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.openapi, TEDSCoreSystem.tedsservicescheduler, "Uses", $techn="", $tags="", $link="")
Rel(Dealer, DCPMobileApplication, "Manages stores, creates quotations", $techn="", $tags="", $link="")
Rel(Administrator, DCPMobileApplication, "Manages system configuration, create staff users", $techn="", $tags="", $link="")
Rel(WorkshopStaff, DCPMobileApplication, "Performs data entry, performs services, creates quotations", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml