@startuml
set separator none
title Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(TEDSCoreSystem, "TEDS Core System", $descr="DOS platform including microservices and core business logic", $tags="", $link="")
System(PlateScannerExternalAPI, "Plate Scanner External API", $descr="Third-party number plate and VIN scanning API", $tags="", $link="")

System_Boundary("DCPMobileApplication_boundary", "DCP Mobile Application", $tags="") {
  Container(DCPMobileApplication.PlateScanner, "Plate Scanner", $techn="", $descr="Number plate and VIN scanner", $tags="", $link="")
}

Rel(DCPMobileApplication.PlateScanner, PlateScannerExternalAPI, "Send images of number plates & VINs", $techn="JSON/HTTPS", $tags="", $link="")
Rel(PlateScannerExternalAPI, DCPMobileApplication.PlateScanner, "Receives text number plates & VINs", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem, DCPMobileApplication.PlateScanner, "Accesses camera to take pictures of number plates & VINs", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml