@startuml
set separator none
title Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(TEDSCoreSystem, "TEDS Core System", $descr="DOS platform including microservices and core business logic", $tags="", $link="")
System(PS9Application, "PS9 Application", $descr="Mobile login application", $tags="", $link="")
System(SpyderApplication, "Spyder Application", $descr="Mobile login application", $tags="", $link="")
System(WyzAutoApplication, "WyzAuto Application", $descr="Mobile login application", $tags="", $link="")
System(MARSApplication, "MARS Application", $descr="Mobile login application", $tags="", $link="")

System_Boundary("ReferentialSystem_boundary", "Referential System", $tags="") {
  Container(ReferentialSystem.TEDSTyrereferential, "TEDS Tyre referential", $techn="", $descr="TEDS product and services referential", $tags="", $link="")
}

Rel(PS9Application, ReferentialSystem.TEDSTyrereferential, "Gets Michelin tyre referential data", $techn="kafka", $tags="", $link="")
Rel(SpyderApplication, ReferentialSystem.TEDSTyrereferential, "Gets non-tyre referential data", $techn="kafka", $tags="", $link="")
Rel(WyzAutoApplication, ReferentialSystem.TEDSTyrereferential, "Gets non-tyre referential data", $techn="API", $tags="", $link="")
Rel(MARSApplication, ReferentialSystem.TEDSTyrereferential, "Gets non-tyre referential data", $techn="Manual dump", $tags="", $link="")
Rel(ReferentialSystem.TEDSTyrereferential, TEDSCoreSystem, "Stores referential", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml