@startuml
set separator none
title API Application - Dynamic

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container_Boundary("TEDSCoreSystem.APIApplication_boundary", "API Application", $tags="") {
  Component(TEDSCoreSystem.APIApplication.SignInController, "Sign In Controller", $techn="Spring MVC RestController", $descr="Allows users to sign in", $tags="", $link="")
  Component(TEDSCoreSystem.APIApplication.SecurityComponent, "Security Component", $techn="Spring Security", $descr="Authentication & authorization", $tags="", $link="")
}

Container(TEDSCoreSystem.SinglePageApplication, "Single-Page Application", $techn="React + TypeScript", $descr="Internet banking UI in the browser", $tags="", $link="")

Rel(TEDSCoreSystem.SinglePageApplication, TEDSCoreSystem.APIApplication.SignInController, "1. POST /signin", $techn="JSON/HTTPS", $tags="", $link="")
Rel(TEDSCoreSystem.APIApplication.SignInController, TEDSCoreSystem.APIApplication.SecurityComponent, "2. validate()", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.APIApplication.SecurityComponent, TEDSCoreSystem.APIApplication.SignInController, "3. JWT", $techn="", $tags="", $link="")
Rel(TEDSCoreSystem.APIApplication.SignInController, TEDSCoreSystem.SinglePageApplication, "4. 200 OK + JWT", $techn="JSON/HTTPS", $tags="", $link="")

SHOW_LEGEND(true)
@enduml